title: Annual European Bioinformatics Core Community (AEBC2)
logo: /assets/img/bfxwork.jpg
description: Community-driven exchange on science and operations in bioinformatics core facilities across Europe.
safe: true
show_downloads: false
theme: jekyll-theme-minimal
